# Generated by Django 5.0.6 on 2024-06-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserE',
        ),
        migrations.AddField(
            model_name='task',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ToDo.usere'),
            preserve_default=False,
        ),
    ]
